# Kickstart container config file - see https://gitub.com/c7lab/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-gaia"

apache_fallback_resource: "/index.php"
http_port: 4000


config_file:
  template: "config.php.dist"
  target: "config.php"


command:
  build:
    #- "echo \"www-data   ALL = (ALL) NOPASSWD: /usr/bin/docker\" | sudo tee --append /etc/sudoers"
    #- "sudo apt-get -y install haproxy"
    - "sudo scripts/install.sh"
    - "composer update"
    #- "sudo chmod 777 /srv"


  run:
    - "sudo scripts/update.sh"

  dev:
    - "sudo scripts/update.sh"