version: 1
from: "infracamp/kickstart-flavor-gaia:latest"

apache_fallback_resource: "/index.php"
http_port: 4000

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "sudo scripts/install.sh"
    - "composer update"

  run:
    - "sudo scripts/update.sh"

  dev:
    - "sudo scripts/update.sh"

  interval:
    - "sudo /opt/bin/update-daemon-nginx.sh"